@startuml

hide empty description

' 空仓时的可能状态转换
[*]  --> 空仓
空仓 --> 全仓持有沪深300ETF : 沪深300动量值较大
空仓 --> 全仓持有中证500ETF : 中证500动量值较大

' 空仓沪深300ETF时的可能状态转换
全仓持有沪深300ETF --> 全仓持有对冲证券 : 沪深300出现负动量

' 空仓中证500ETF时的可能状态转换
全仓持有中证500ETF --> 全仓持有对冲证券 : 中证500均出现负动量

' 空仓对冲状态时的可能状态转换
全仓持有对冲证券 --> 全仓持有沪深300ETF : 沪深300动量值较大
全仓持有对冲证券 --> 全仓持有中证500ETF : 中证500动量值较大


@enduml
