@startuml

Beverage <|-- HouseBlend
Beverage <|-- DarkRoast
Beverage <|-- Decaf
Beverage <|-- Espresso
Beverage <|- HouseBlendWithMilk
Beverage <|- DarkRoastWithMilk
Beverage <|- DecafWithMilk
Beverage <|- EspressoWithMilk
HouseBlendWithSoy --|> Beverage
DarkRoastWithSoy --|> Beverage
DecafWithSoy --|> Beverage
EspressoWithSoy --|> Beverage
HouseBlendWithWhip -|> Beverage
DarkRoastWithWhip -|> Beverage
DecafWithWhip -|> Beverage
EspressoWithWhip -|> Beverage

class Beverage {
  description
  getDescription()
  cost()
}
'-------------------------------------------------------------------------------'
class HouseBlend {
  cost()
}

class DarkRoast {
  cost()
}

class Decaf {
  cost()
}

class Espresso {
  cost()
}

'-------------------------------------------------------------------------------'
class HouseBlendWithMilk {
  cost()
}

class DarkRoastWithMilk {
  cost()
}

class DecafWithMilk {
  cost()
}

class EspressoWithMilk {
  cost()
}

'-------------------------------------------------------------------------------'
class HouseBlendWithSoy {
  cost()
}

class DarkRoastWithSoy {
  cost()
}

class DecafWithSoy {
  cost()
}

class EspressoWithSoy {
  cost()
}

'-------------------------------------------------------------------------------'
class HouseBlendWithWhip {
  cost()
}

class DarkRoastWithWhip {
  cost()
}

class DecafWithWhip {
  cost()
}

class EspressoWithWhip {
  cost()
}

@enduml
