@startuml

class Component {
  methodA()
  methodB()
}

Component <|-- ConcreteComponent
Component <|-- Decorator
Component <-- Decorator

class ConcreteComponent {
  methodA()
  methodB()
}

class Decorator {
  methodA()
  methodB()
}

Decorator <|-- ConcreteDecoratorA
Decorator <|-- ConcreteDecoratorB

class ConcreteDecoratorA {
  Component wrappedObj

  methodA()
  methodB()
  newBehavior()
}

class ConcreteDecoratorB {
  Component wrappedObj
  Object newState

  methodA()
  methodB()
}

@enduml
