@startuml

class Client {

}

class AbstractFactory {
  {abstract} CreateProductA()
  {abstract} CreateProductB()
}

Client -> AbstractFactory

class ConcreteFactory1 {
  CreateProductA()
  CreateProductB()
}
class ConcreteFactory2 {
  CreateProductA()
  CreateProductB()
}

AbstractFactory <|.. ConcreteFactory1
AbstractFactory <|.. ConcreteFactory2

' Product Series

class AbstractProductA {

}

AbstractProductA <|.. ProductA1
AbstractProductA <|.. ProductA2

class AbstractProductB {

}

AbstractProductB <|.. ProductB1
AbstractProductB <|.. ProductB2

ConcreteFactory1 --> ProductA1
ConcreteFactory1 --> ProductB1

ConcreteFactory2 --> ProductA2
ConcreteFactory2 --> ProductB2

Client --> AbstractProductA
Client --> AbstractProductB

@enduml
